CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(63) NOT NULL,
    email VARCHAR(63) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS PUBLIC.REQUESTS
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(63) NOT NULL,
    user_id BIGINT not null,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    constraint pk_request primary key (request_id),
    CONSTRAINT userInRequest_FK FOREIGN KEY (user_id) REFERENCES Public.Users(user_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.ITEMS
(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME VARCHAR(63) NOT NULL,
    DESCRIPTION VARCHAR(63) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    user_id BIGINT not null,
    request_id BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT ownerInBooking_FK FOREIGN KEY (user_id) REFERENCES Public.USERS(user_id),
    CONSTRAINT request_FK FOREIGN KEY (request_id) REFERENCES Public.REQUESTS(request_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.BOOKINGS
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT not null,
    booker_id BIGINT not null,
    status VARCHAR(15) not null,
    constraint pk_booking primary key (booking_id),
    CONSTRAINT itemInBooking_FK FOREIGN KEY (item_id) REFERENCES Public.ITEMS(item_id),
    CONSTRAINT bookerInBooking_FK FOREIGN KEY (booker_id) REFERENCES Public.Users(user_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.COMMENTS
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(500) not null,
    item_id BIGINT not null,
    user_id BIGINT not null,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    constraint pk_comment primary key (comment_id),
    CONSTRAINT itemInComment_FK FOREIGN KEY (item_id) REFERENCES Public.ITEMS(item_id),
    CONSTRAINT userInComment_FK FOREIGN KEY (user_id) REFERENCES Public.Users(user_id)
);